version: "3.8"

# Setup Development Environment

services:
  mongodb:
    image: mongo
    volumes:
      - data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    command: mongod --auth
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017
    depends_on:
      - mongodb
  
  
  backend:
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    environment:
      - PORT=5000
      - DB_URI=mongodb://root:example@mongodb:27017
      - JWT_SECRET=reallyimpressivlystrongjwtsecret
      - NODE_ENV=development
    depends_on:
      - mongodb
  
  
  frontend:
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app/client
    build:
      context: client
      dockerfile: Dockerfile.dev
    environment:
      - REACT_APP_BACKEND_URI=http://localhost:5000
      - PORT=3000
      - NODE_ENV=development
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
